FROM node:18.16.0-alpine as build

WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH

COPY package.json /app
COPY package-lock.json /app

RUN npm ci --silent
RUN npm install -D postcss-cli --silent
#RUN npm install react-scripts@3.4.1 -g --silent

COPY . .

RUN npm run test:ci
RUN npm run build
RUN npm run build:css

# production environment
FROM nginx:stable-alpine
COPY --from=build /app/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]