FROM node:18.16.0-alpine as build

WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH

COPY package.json /app
COPY package-lock.json /app

RUN npm ci --silent
RUN npm install -D postcss-cli --silent
#RUN npm install react-scripts@3.4.1 -g --silent

COPY . .

# OVERWRITE ENV VARIABLE
RUN echo "REACT_APP_API_URL=https://chat-backend.ikerocio.com/" > .env

RUN npm run lint:fix
RUN npm run build
RUN npm run build:css

# production environment
FROM nginx:stable-alpine

# self-signed-certs
COPY nginx/docker-cert-entrypoint.sh /
RUN chmod +x /docker-cert-entrypoint.sh && /docker-cert-entrypoint.sh

COPY nginx/nginx.conf /etc/nginx/conf.d/nginx.conf

COPY --from=build /app/build /usr/share/nginx/html
EXPOSE 443
CMD ["nginx", "-g", "daemon off;"]