services:
  back-fast-gpt-prod:
    build:
      context: ./backend
    image: iocio005/back-fast-gpt-prod:latest
    ports:
      - "5000:80"
    environment:
      - OPENAI_API_KEY=<you api key here>
      - MAX_TOKENS=1000
      - ALLOWED_ORIGINS=http://localhost:3000,https://localhost:8443
  front-fast-gpt-prod:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    image: iocio005/front-fast-gpt-prod:latest
    ports:
      - "8443:443"
