services:
  back-fast-gpt-prod:
    build:
      context: ./backend
    image: iocio005/back-fast-gpt-prod:latest
    ports:
      - "5000:80"
    environment:
      - OPENAI_API_KEY=<your_apikey>
      - MAX_TOKENS=1000
      - CORS_ORIGINS=http://localhost
  front-fast-gpt-prod:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    image: iocio005/front-fast-gpt-prod:latest
    ports:
      - "8080:80"
    environment:
      - REACT_APP_API_URL="http://localhost:5000/"
