services:
  back-fast-gpt-prod:
    image: iocio005/back-fast-gpt-prod:latest
    ports:
      - "5000:80"
    environment:
      - OPEN_API_KEY=<yourapiykey>
      - MAX_TOKENS=1000
      - CORS_ORIGINS=http://localhost:8080
  front-fast-gpt-prod:
    image: iocio005/front-fast-gpt-prod:latest
    ports:
      - "8080:80"
    environment:
      - REACT_APP_API_URL="http://localhost:5000/"
