services:
  back-fast-gpt:
    build:
      context: ./backend
    ports:
      - "5000:80"
      - "5678:5678"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/app:/app
    command: "python -m debugpy --listen 0.0.0.0:5678 --wait-for-client /app/main.py --reload"
    #command: "python -m debugpy --listen 0.0.0.0:5678 -m pytest --debug"

  front-fast-gpt:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env
    volumes:
      - ./frontend:/app
