services:
  back-fast-gpt-prod:
    image: iocio005/back-fast-gpt-prod:latest
    ports:
      - "5000:80"
    environment:
      - OPENAI_API_KEY=<apikey>
      - ALLOWED_ORIGINS=https://chat.ikerocio.com
  front-fast-gpt-prod:
    image: iocio005/front-fast-gpt-prod:latest
    ports:
      - "443:443"