name: Python tests with Docker
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:20.10.8-dind
    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker-compose build
      - name: Run the Docker container
        run: docker-compose run --rm back-fast-gpt pytest -vv
