name: Python tests with Docker
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:20.10.8-dind
    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: |
          echo -n "OPEN_API_KEY=MY_FAKE_APIKEY" > backend/.env
          echo -n "MAX_TOKENS=1000" >> backend/.env
          echo -n "CORS_ORIGINS=http://localhost:3000" >> backend/.env
          echo -n "REACT_APP_API_URL=http://localhost:5000/" > frontend/.env
          docker-compose build
      - name: Run the Docker container
        run: |
          docker-compose run --rm back-fast-gpt pytest -vv
