name: Github Actions
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  tests:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:20.10.8-dind
    steps:
      - uses: actions/checkout@v2
      - name: Prepare env files
        run: |
          echo -n "OPEN_API_KEY=MY_FAKE_APIKEY" > backend/.env
          echo -n "MAX_TOKENS=1000" >> backend/.env
          echo -n "CORS_ORIGINS=http://localhost:3000" >> backend/.env
          echo -n "REACT_APP_API_URL=http://localhost:5000/" > frontend/.env
      - name: Build the Docker image
        run: |
          docker-compose -f docker-compose.ci.yml build
      - name: Python linting
        run: |
          docker-compose -f docker-compose.ci.yml run --rm back-fast-gpt ruff .
          docker-compose -f docker-compose.ci.yml run --rm back-fast-gpt isort .
          docker-compose -f docker-compose.ci.yml run --rm back-fast-gpt black .
      - name: Test backend container
        run: |
          docker-compose -f docker-compose.ci.yml run --rm back-fast-gpt pytest --cov=. --cov-report html
      - name: Test frontend container
        run: |
          docker-compose -f docker-compose.ci.yml run --rm front-fast-gpt npm run test:coverage
      - name: Upload backend coverage
        uses: actions/upload-artifact@v2
        with:
          name: Backend coverage
          path: backend_coverage
      - name: Upload frontend coverage
        uses: actions/upload-artifact@v2
        with:
          name: Backend coverage
          path: frontend/coverage/lcov-report